# NEXUS Documentation Generator - Global View Generator
"""
Generates global architecture views and documentation.
"""

from datetime import datetime
from pathlib import Path

from ..config import DocGeneratorConfig, FolderInfo, ModuleInfo
from .mermaid_generator import MermaidGenerator


class GlobalViewGenerator:
    """Generates global architecture documentation."""

    def __init__(self, config: DocGeneratorConfig):
        self.config = config
        self.mermaid_gen = MermaidGenerator(config)

    def generate(
        self,
        modules: list[ModuleInfo],
        dep_graph,
        folders: list[FolderInfo]
    ) -> None:
        """Generate all global views."""
        output_dir = self.config.mermaid_output_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate global architecture document
        self._generate_architecture(modules, dep_graph, folders, output_dir)

        # Generate workflow maps
        self._generate_workflow_map(modules, output_dir)

    def _generate_architecture(
        self,
        modules: list[ModuleInfo],
        dep_graph,
        folders: list[FolderInfo],
        output_dir: Path
    ) -> None:
        """Generate GLOBAL_ARCHITECTURE.md"""
        lines = [
            "# NEXUS Global Architecture",
            "",
            f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
            "## System Overview",
            "",
            "```mermaid",
            self._generate_overview_diagram(folders),
            "```",
            "",
            "---",
            "",
            "## Module Hierarchy",
            "",
            "```mermaid",
            self._generate_hierarchy_diagram(folders),
            "```",
            "",
            "---",
            "",
            "## Core Modules",
            "",
            "| Module | Purpose | Key Classes |",
            "|--------|---------|-------------|",
        ]

        # Add core modules table
        core_modules = self._get_core_modules(folders, modules)
        for mod_info in core_modules:
            key_classes = ", ".join(mod_info["key_classes"][:3]) or "_None_"
            lines.append(
                f"| [{mod_info['name']}]({mod_info['path']}/README.md) | "
                f"{mod_info['purpose']} | {key_classes} |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## Statistics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
        ])

        # Calculate statistics
        stats = self._calculate_stats(modules, folders)
        for key, value in stats.items():
            lines.append(f"| {key} | {value:,} |")

        lines.extend([
            "",
            "---",
            f"*Auto-generated by nexus-doc-generator*",
        ])

        content = "\n".join(lines)
        (output_dir / "GLOBAL_ARCHITECTURE.md").write_text(content, encoding="utf-8")

    def _generate_overview_diagram(self, folders: list[FolderInfo]) -> str:
        """Generate system overview flowchart."""
        # Find top-level packages
        top_level = [f for f in folders if len(f.path.parts) == 1]

        nodes = []
        edges = []

        # Central node
        nodes.append({"id": "nexus", "label": "NEXUS", "shape": "stadium"})

        # Top-level packages
        for i, folder in enumerate(top_level[:10]):
            node_id = f"pkg_{i}"
            nodes.append({
                "id": node_id,
                "label": folder.name,
                "shape": "box"
            })
            edges.append({"from": "nexus", "to": node_id})

        return self.mermaid_gen.flowchart(nodes, edges, direction="TB")

    def _generate_hierarchy_diagram(self, folders: list[FolderInfo]) -> str:
        """Generate module hierarchy diagram."""
        nodes = []
        edges = []

        # Find core packages
        core_folders = [f for f in folders if "core" in str(f.path)]

        for i, folder in enumerate(core_folders[:15]):
            node_id = f"f_{i}"
            nodes.append({
                "id": node_id,
                "label": folder.name,
                "shape": "box"
            })

            # Add edge from parent
            parent_path = folder.path.parent
            parent_id = None
            for j, other in enumerate(core_folders):
                if str(other.path) == str(parent_path):
                    parent_id = f"f_{j}"
                    break

            if parent_id:
                edges.append({"from": parent_id, "to": node_id})

        return self.mermaid_gen.flowchart(nodes, edges, direction="TB")

    def _generate_workflow_map(
        self,
        modules: list[ModuleInfo],
        output_dir: Path
    ) -> None:
        """Generate WORKFLOWS_MAP.md"""
        lines = [
            "# NEXUS Workflows Map",
            "",
            f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
        ]

        # Find workflow-related modules
        workflow_modules = [
            m for m in modules
            if any(kw in m.name.lower() for kw in
                   ["flow", "pipe", "handler", "executor", "orchestr"])
        ]

        if workflow_modules:
            lines.append("## Identified Workflow Modules")
            lines.append("")
            lines.append("| Module | Classes | Functions |")
            lines.append("|--------|---------|-----------|")

            for mod in workflow_modules:
                lines.append(
                    f"| `{mod.path}` | {mod.class_count} | {mod.function_count} |"
                )

            lines.append("")

        # Add FSM states if found
        fsm_modules = [m for m in modules if "fsm" in m.name.lower() or "state" in m.name.lower()]
        if fsm_modules:
            lines.extend([
                "## FSM State Modules",
                "",
            ])

            for mod in fsm_modules:
                if mod.classes:
                    lines.append(f"### {mod.name}")
                    lines.append("")
                    for cls in mod.classes:
                        if not cls.name.startswith("_"):
                            lines.append(f"- `{cls.name}`")
                    lines.append("")

        lines.extend([
            "---",
            "*Auto-generated by nexus-doc-generator*",
        ])

        content = "\n".join(lines)
        (output_dir / "WORKFLOWS_MAP.md").write_text(content, encoding="utf-8")

    def _get_core_modules(
        self,
        folders: list[FolderInfo],
        modules: list[ModuleInfo]
    ) -> list[dict]:
        """Get information about core modules."""
        core_info = []

        # Find core subfolders
        core_folders = [
            f for f in folders
            if str(f.path).startswith("core") and len(f.path.parts) == 2
        ]

        for folder in core_folders:
            # Get modules in this folder
            folder_modules = [
                m for m in modules
                if str(m.path).startswith(str(folder.path))
            ]

            # Get key classes
            key_classes = []
            for mod in folder_modules:
                for cls in mod.classes:
                    if not cls.name.startswith("_"):
                        key_classes.append(cls.name)

            # Get purpose from init docstring
            purpose = "_No description_"
            init_mod = next(
                (m for m in folder_modules if m.name == "__init__"),
                None
            )
            if init_mod and init_mod.docstring:
                purpose = init_mod.docstring.split("\n")[0].strip()

            core_info.append({
                "name": folder.name,
                "path": folder.path,
                "purpose": purpose,
                "key_classes": key_classes,
            })

        return core_info

    def _calculate_stats(
        self,
        modules: list[ModuleInfo],
        folders: list[FolderInfo]
    ) -> dict:
        """Calculate global statistics."""
        python_files = sum(len(f.python_files) for f in folders)
        test_files = sum(
            1 for f in folders for pf in f.python_files
            if "test" in pf.name.lower()
        )

        return {
            "Total Python Files": python_files,
            "Total Lines of Code": sum(m.loc for m in modules),
            "Total Classes": sum(m.class_count for m in modules),
            "Total Functions": sum(m.function_count for m in modules),
            "Core Modules": len([f for f in folders if str(f.path).startswith("core")]),
            "Test Files": test_files,
        }
