"""
Mode Selector - Sprint 9 Hybrid Swarm Engine

Selects the optimal collaboration mode using:
1. TaskAnalysis (complexity, domains)
2. DyLAN importance scores (AgentPool)
3. Mode characteristics matching
4. Historical performance

Works with AgentPool to provide data-driven mode selection.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from datetime import datetime

from .collaboration_modes import (
    CollaborationMode,
    ModeCharacteristics,
    MODE_CHARACTERISTICS,
    get_mode_characteristics
)
from .task_analyzer import TaskAnalysis, TaskComplexity, TaskDomain
from .agent_metrics import AgentPool, AgentProfile


@dataclass
class AgentAssignment:
    """Assignment of an agent to a role in a collaboration mode"""
    agent_id: str
    role: str  # "lead", "support", "red", "blue", "equal", "specialist"
    subtask: Optional[str] = None
    confidence: float = 0.5


@dataclass
class ModeProposal:
    """
    Proposal for a collaboration mode.

    Generated by ModeSelector, may be modified by negotiation.
    """
    mode: CollaborationMode
    confidence: float  # 0.0-1.0
    agent_assignments: List[AgentAssignment]
    reasoning: str
    alternatives: List[Tuple[CollaborationMode, float]] = field(
        default_factory=list
    )
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict:
        return {
            "mode": self.mode.value,
            "confidence": round(self.confidence, 3),
            "agent_assignments": [
                {
                    "agent_id": a.agent_id,
                    "role": a.role,
                    "subtask": a.subtask,
                    "confidence": round(a.confidence, 3)
                }
                for a in self.agent_assignments
            ],
            "reasoning": self.reasoning,
            "alternatives": [
                {"mode": m.value, "score": round(s, 3)}
                for m, s in self.alternatives[:3]
            ],
            "timestamp": self.timestamp.isoformat()
        }


class ModeSelector:
    """
    Selects optimal collaboration mode using DyLAN scoring.

    Combines task analysis with agent performance history
    to recommend the best collaboration mode.
    """

    def __init__(
        self,
        agent_pool: Optional[AgentPool] = None,
        history_weight: float = 0.3
    ):
        """
        Initialize ModeSelector.

        Args:
            agent_pool: AgentPool with performance history
            history_weight: Weight given to historical performance (0-1)
        """
        self.agent_pool = agent_pool
        self.history_weight = history_weight
        self.selection_history: List[Dict] = []

    def select_mode(
        self,
        task_analysis: TaskAnalysis,
        available_agents: Optional[List[AgentProfile]] = None
    ) -> ModeProposal:
        """
        Select optimal collaboration mode for a task.

        Args:
            task_analysis: Analysis of the task
            available_agents: Override agents (uses pool if None)

        Returns:
            ModeProposal with recommended mode and assignments
        """
        # Get agents
        if available_agents is None and self.agent_pool:
            available_agents = self.agent_pool.get_active_agents()

        if not available_agents:
            # Fallback: create default profiles
            available_agents = self._create_default_agents()

        # Score all modes
        mode_scores: Dict[CollaborationMode, float] = {}
        for mode in CollaborationMode:
            score = self._score_mode(mode, task_analysis, available_agents)
            mode_scores[mode] = score

        # Select best mode
        best_mode = max(mode_scores, key=mode_scores.get)
        best_score = mode_scores[best_mode]

        # Generate alternatives (sorted by score)
        sorted_modes = sorted(
            mode_scores.items(),
            key=lambda x: x[1],
            reverse=True
        )
        alternatives = [(m, s) for m, s in sorted_modes if m != best_mode]

        # Assign agents
        assignments = self._assign_agents(
            best_mode, task_analysis, available_agents
        )

        # Generate reasoning
        reasoning = self._generate_reasoning(
            best_mode, task_analysis, mode_scores
        )

        proposal = ModeProposal(
            mode=best_mode,
            confidence=best_score,
            agent_assignments=assignments,
            reasoning=reasoning,
            alternatives=alternatives
        )

        # Record selection
        self._record_selection(task_analysis, proposal)

        return proposal

    def _score_mode(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """
        Score a mode for the given task and agents.

        Combines:
        - Complexity fit
        - Domain fit
        - Agent importance scores (DyLAN)
        - Historical performance
        """
        char = get_mode_characteristics(mode)
        score = 0.0

        # 1. Complexity fit (30%)
        complexity_fit = self._score_complexity_fit(char, analysis)
        score += complexity_fit * 0.30

        # 2. Domain fit (25%)
        domain_fit = self._score_domain_fit(char, analysis, agents)
        score += domain_fit * 0.25

        # 3. Agent importance scores - DyLAN (25%)
        dylan_fit = self._score_dylan_fit(mode, analysis, agents)
        score += dylan_fit * 0.25

        # 4. Requirements fit (20%)
        requirements_fit = self._score_requirements_fit(char, analysis)
        score += requirements_fit * 0.20

        return score

    def _score_complexity_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis
    ) -> float:
        """Score how well mode complexity matches task"""
        task_complexity_normalized = analysis.complexity.value / 5.0
        diff = abs(char.complexity_affinity - task_complexity_normalized)
        return 1.0 - diff

    def _score_domain_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """Score how well agent strengths match task domains"""
        # Find Gemini and Claude agents
        gemini = next((a for a in agents if "gemini" in a.agent_id.lower()), None)
        claude = next((a for a in agents if "claude" in a.agent_id.lower()), None)

        if not gemini or not claude:
            return 0.5  # Neutral if agents not found

        score = 0.0
        primary_domain = analysis.primary_domain.value

        # Check if mode's strength fits match task domains
        if primary_domain in char.gemini_strength_fit:
            score += 0.5
        if primary_domain in char.claude_strength_fit:
            score += 0.5

        return min(1.0, score)

    def _score_dylan_fit(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """Score using DyLAN importance scores from agent history"""
        if not agents:
            return 0.5

        primary_domain = analysis.primary_domain.value
        scores = []

        for agent in agents:
            importance = agent.get_task_importance(primary_domain)
            scores.append(importance)

        if not scores:
            return 0.5

        # For modes that benefit from specialist, reward high variance
        # For modes that need collaboration, reward balanced scores
        avg_score = sum(scores) / len(scores)

        if mode == CollaborationMode.SPECIALIST:
            # Reward when one agent clearly better
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return min(1.0, 0.5 + variance)
        else:
            # Reward balanced scores for collaborative modes
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return max(0.0, 1.0 - variance)

    def _score_requirements_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis
    ) -> float:
        """Score based on task requirements"""
        score = 0.5  # Base score

        # Web requirement → prefer parallel (can search while coding)
        if analysis.requires_web and char.parallelism_benefit > 0.5:
            score += 0.2

        # Deep reasoning → prefer ping-pong or lead-support
        if analysis.requires_deep_reasoning:
            if char.mode in [CollaborationMode.PING_PONG, CollaborationMode.LEAD_SUPPORT]:
                score += 0.2

        # Iteration → prefer ping-pong
        if analysis.requires_iteration:
            if char.mode == CollaborationMode.PING_PONG:
                score += 0.3

        # Security → require RED_BLUE
        if analysis.needs_adversarial_mode:
            if char.adversarial:
                score += 0.5
            else:
                score -= 0.3

        return max(0.0, min(1.0, score))

    def _assign_agents(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> List[AgentAssignment]:
        """Assign agents to roles based on mode and task"""
        gemini = next((a for a in agents if "gemini" in a.agent_id.lower()), None)
        claude = next((a for a in agents if "claude" in a.agent_id.lower()), None)

        if not gemini or not claude:
            return []

        assignments = []

        if mode == CollaborationMode.PARALLEL:
            # Assign based on domain strengths
            if analysis.requires_web:
                assignments.append(AgentAssignment(
                    agent_id=gemini.agent_id,
                    role="equal",
                    subtask="research_and_web",
                    confidence=0.8
                ))
                assignments.append(AgentAssignment(
                    agent_id=claude.agent_id,
                    role="equal",
                    subtask="implementation",
                    confidence=0.8
                ))
            else:
                assignments.append(AgentAssignment(
                    agent_id=gemini.agent_id,
                    role="equal",
                    subtask="subtask_1"
                ))
                assignments.append(AgentAssignment(
                    agent_id=claude.agent_id,
                    role="equal",
                    subtask="subtask_2"
                ))

        elif mode == CollaborationMode.SEQUENTIAL:
            # Gemini first (research), Claude second (implementation)
            if TaskDomain.RESEARCH in analysis.domains:
                first, second = gemini, claude
            else:
                first, second = claude, gemini

            assignments.append(AgentAssignment(
                agent_id=first.agent_id,
                role="first",
                confidence=0.7
            ))
            assignments.append(AgentAssignment(
                agent_id=second.agent_id,
                role="second",
                confidence=0.7
            ))

        elif mode == CollaborationMode.LEAD_SUPPORT:
            # Assign lead based on domain fit
            if analysis.claude_fit_score > analysis.gemini_fit_score:
                lead, support = claude, gemini
            else:
                lead, support = gemini, claude

            assignments.append(AgentAssignment(
                agent_id=lead.agent_id,
                role="lead",
                confidence=max(analysis.gemini_fit_score, analysis.claude_fit_score)
            ))
            assignments.append(AgentAssignment(
                agent_id=support.agent_id,
                role="support",
                confidence=0.6
            ))

        elif mode == CollaborationMode.PING_PONG:
            # Both equal, alternating
            assignments.append(AgentAssignment(
                agent_id=gemini.agent_id,
                role="equal",
                confidence=0.7
            ))
            assignments.append(AgentAssignment(
                agent_id=claude.agent_id,
                role="equal",
                confidence=0.7
            ))

        elif mode == CollaborationMode.SPECIALIST:
            # Single agent based on best fit
            if analysis.claude_fit_score > analysis.gemini_fit_score:
                specialist = claude
            else:
                specialist = gemini

            assignments.append(AgentAssignment(
                agent_id=specialist.agent_id,
                role="specialist",
                confidence=max(analysis.gemini_fit_score, analysis.claude_fit_score)
            ))

        elif mode == CollaborationMode.RED_BLUE:
            # Assign red/blue roles
            # Claude as Blue (proposer) - better at architecture
            # Gemini as Red (attacker) - good at finding edge cases
            assignments.append(AgentAssignment(
                agent_id=claude.agent_id,
                role="blue",
                subtask="propose_and_defend",
                confidence=0.8
            ))
            assignments.append(AgentAssignment(
                agent_id=gemini.agent_id,
                role="red",
                subtask="attack_and_verify",
                confidence=0.8
            ))

        return assignments

    def _generate_reasoning(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        scores: Dict[CollaborationMode, float]
    ) -> str:
        """Generate human-readable reasoning for mode selection"""
        char = get_mode_characteristics(mode)

        reasons = []

        # Complexity reason
        complexity_name = analysis.complexity.name.lower()
        reasons.append(f"Task complexity: {complexity_name}")

        # Domain reason
        domain_str = ", ".join(d.value for d in analysis.domains[:2])
        reasons.append(f"Domains: {domain_str}")

        # Agent fit reason
        if analysis.recommended_lead == "claude":
            reasons.append("Claude has higher fit score (coding expertise)")
        elif analysis.recommended_lead == "gemini":
            reasons.append("Gemini has higher fit score (research/web)")
        else:
            reasons.append("Balanced agent fit (collaborative mode)")

        # Mode-specific reason
        reasons.append(char.when_to_use)

        # Score
        reasons.append(f"Selection confidence: {scores[mode]:.0%}")

        return " | ".join(reasons)

    def _create_default_agents(self) -> List[AgentProfile]:
        """Create default agent profiles when pool unavailable"""
        return [
            AgentProfile(
                agent_id="gemini_primary",
                provider="gemini",
                model="gemini-3-pro-preview"
            ),
            AgentProfile(
                agent_id="claude_opus",
                provider="claude",
                model="claude-opus-4-5-20251101"
            )
        ]

    def _record_selection(
        self,
        analysis: TaskAnalysis,
        proposal: ModeProposal
    ):
        """Record selection for future analysis"""
        record = {
            "timestamp": datetime.now().isoformat(),
            "task_complexity": analysis.complexity.name,
            "primary_domain": analysis.primary_domain.value,
            "selected_mode": proposal.mode.value,
            "confidence": proposal.confidence
        }
        self.selection_history.append(record)

        # Keep only last 100 selections
        if len(self.selection_history) > 100:
            self.selection_history = self.selection_history[-100:]

    def get_selection_stats(self) -> Dict:
        """Get statistics about mode selections"""
        if not self.selection_history:
            return {"total_selections": 0}

        mode_counts: Dict[str, int] = {}
        for record in self.selection_history:
            mode = record["selected_mode"]
            mode_counts[mode] = mode_counts.get(mode, 0) + 1

        avg_confidence = sum(
            r["confidence"] for r in self.selection_history
        ) / len(self.selection_history)

        return {
            "total_selections": len(self.selection_history),
            "mode_distribution": mode_counts,
            "average_confidence": round(avg_confidence, 3)
        }
