"""
NEXUS V12.4 - Intelligence Package

P5.6 Phase 6: Package Consolidation

Consolidated intelligence components for swarm coordination, agent evolution, advanced reasoning, and hive mind orchestration.

## 📦 Subpackages

- **swarm/**: Hybrid Swarm Engine with 6 collaboration modes (PARALLEL, SEQUENTIAL, LEAD_SUPPORT, PING_PONG, SPECIALIST, RED_BLUE)
- **evolution/**: Self-modification, lineage tracking, tiered validation, agent reaper, auto-specializer
- **reasoning/**: Graph of Thought (GoT), metacognitive monitoring, reasoning quality scoring, confidence calibration
- **hive_mind/**: TRUE HIVE MIND with 7 phases, adaptive debate, knowledge consolidation, swarm bridge

## 🎯 Key Features

### Hybrid Swarm Engine
```python
from core.intelligence import HybridSwarmEngine, CollaborationMode

engine = HybridSwarmEngine(agent_pool, model_router, config)
result = await engine.process_task("Fix the auth bug", blackboard)
```

### Evolution & Lineage
```python
from core.intelligence import EvolutionManager, TieredValidator

manager = EvolutionManager(...)
result = await manager.evolve_agent(task="performance")
```

### Advanced Reasoning
```python
from core.intelligence import MetacognitiveMonitor, ConfidenceCalibrator

monitor = get_metacognitive_monitor()
anomaly = monitor.detect_anomaly(agent_response)
```

### TRUE HIVE MIND
```python
from core.intelligence import TrueHiveMind

hive = TrueHiveMind(workspace_path, config)
result = await hive.process_task("Complex multi-step task")
```

## 📊 Migration Impact

**Statistics:**
- Files migrated: TBD
- Import updates: TBD
- Commit: TBD
- Impact: TBD

---
**Status:** P5.6 Phase 6 IN PROGRESS | **Version:** V12.4
"""

# Swarm exports (96 items)
from core.intelligence.swarm import (
    # Agent Metrics
    AgentInvocationResult,
    AgentProfile,
    AgentPool,
    create_default_pool,
    # Collaboration Modes
    CollaborationMode,
    ModeCharacteristics,
    MODE_CHARACTERISTICS,
    get_mode_characteristics,
    get_all_modes,
    get_adversarial_modes,
    get_parallel_modes,
    suggest_mode_for_complexity,
    # Task Analyzer
    TaskComplexity,
    TaskDomain,
    TaskAnalysis,
    TaskAnalyzer,
    # Mode Selector
    AgentAssignment,
    ModeProposal,
    ModeSelector,
    # Negotiation Protocol
    NegotiationStatus,
    NegotiationProposal,
    HybridNegotiationMessage,
    NegotiationResult,
    NegotiationProtocol,
    extract_negotiate_json,
    # Mode Executors
    ExecutionStatus,
    AgentResponse,
    ExecutionContext,
    ExecutionResult,
    ModeExecutor,
    ParallelExecutor,
    SequentialExecutor,
    LeadSupportExecutor,
    PingPongExecutor,
    SpecialistExecutor,
    RedBlueExecutor,
    EXECUTOR_REGISTRY,
    get_executor,
    # Hybrid Swarm Engine
    SwarmPhase,
    SwarmResult,
    HybridSwarmEngine,
    # Session Manager
    SessionStatus,
    SessionMode,
    AgentSession,
    TaskSession,
    SwarmSessionManager,
    generate_task_id,
    # Task Completion Validator
    TaskCompletionValidator,
    CompletionCriteria,
    ValidationResult,
    get_adaptive_max_rounds,
    # Service Layer
    SwarmService,
    SwarmServiceResult,
    SwarmStatus,
    # V12.4: Task Queue
    SwarmTaskQueue,
    SwarmTask,
    SwarmTaskStatus,
    QueueStats,
    get_task_queue,
    reset_task_queue,
    # V12.4: Result Aggregator
    ResultAggregator,
    MergeStrategy,
    MergeResult,
    AggregatorStats,
    get_aggregator,
    reset_aggregator,
    # V12.4: Strategy Memory
    StrategyMemory,
    StrategyRecord,
    ModeEffectiveness,
    ModeSuggestion,
    StrategyStats,
    get_strategy_memory,
    reset_strategy_memory,
    # V12.4: Negotiation Tracker
    NegotiationTracker,
    NegotiationTurn,
    NegotiationRecord,
    NegotiationStats,
    get_negotiation_tracker,
    reset_negotiation_tracker,
    # V12.4: Mode Effectiveness Evaluator
    ModeEffectivenessEvaluator,
    ModeEvaluation,
    ModeEffectivenessSummary,
    EvaluatorStats,
    get_mode_evaluator,
    reset_mode_evaluator,
    # V12.4: Agent Role Tracker
    AgentRoleTracker,
    RoleAssignment,
    AgentRoleProfile,
    RoleTrackerStats,
    get_role_tracker,
    reset_role_tracker,
    # V12.4: Dynamic Role Assigner
    DynamicRoleAssigner,
    CapabilityProposal,
    RoleScore,
    RoleAssignmentResult,
    RoleType,
    AssignerStats,
    get_dynamic_role_assigner,
    reset_dynamic_role_assigner,
    # V12.4: Scaling Heuristics
    ScalingHeuristicEvaluator,
    ScalingRecommendation,
    CoordinationType,
    TaskCharacteristic,
    ScalingStats,
    get_scaling_heuristics,
    reset_scaling_heuristics,
)

# Evolution exports (30 items)
from core.intelligence.evolution import (
    EvolutionManager,
    EvolutionService,
    EvolutionServiceResult,
    _get_evolution_service,
    MutationProposal,
    BrainstormResult,
    ChildCreationResult,
    EvaluationResult,
    PromotionResult,
    ArchiveResult,
    EvolutionResult,
    SpecializationResult,
    EvolutionStatus,
    EvolutionContext,
    EvolutionPhaseStatus,
    load_lineage,
    add_child,
    get_ancestry,
    sign_birth_certificate,
    run_benchmarks,
    compare_to_parent,
    select_winner,
    ChildValidator,
    ValidationResult as EvolutionValidationResult,
    FullValidationResult,
    SafetyGate,
    AutoPromotionDecision,
    TieredValidator,
    ValidationTier,
    TieredValidationResult,
    TierResult,
    AgentReaper,
    ReaperConfig,
    ReaperReport,
    ArchivalCandidate,
    AutoSpecializer,
    SpecializationConfig,
    SpecializationProposal,
    DomainProfile,
    MutationTracker,
    MutationRecord,
    AgentPerformance,
    LineageNode,
    get_mutation_tracker,
    reset_mutation_tracker,
    StrategyPerformanceTracker,
    StrategyApplication,
    StrategyMetrics,
    StrategyRecommendation,
    TrackerStats,
    get_strategy_tracker,
    reset_strategy_tracker,
)

# Reasoning exports (60+ items)
from core.intelligence.reasoning import (
    GOT_AVAILABLE,
    GraphOfThought,
    ThoughtNode,
    ThoughtGraph,
    ThoughtStatus,
    ThoughtType,
    ThoughtEvaluator,
    ThoughtScore,
    EvaluationResult as ThoughtEvaluationResult,
    EvaluatorStats as ThoughtEvaluatorStats,
    get_thought_evaluator,
    reset_thought_evaluator,
    ReasoningQualityScorer,
    ReasoningEvaluation,
    AgentReasoningProfile,
    ScorerStats,
    get_quality_scorer,
    reset_quality_scorer,
    CognitiveDegradationDetector,
    DegradationSignal,
    DegradationReason,
    Mitigation,
    DetectorStats,
    get_degradation_detector,
    reset_degradation_detector,
    EvaluationPanel,
    EvalDimension,
    DimensionScore,
    PanelResult,
    get_evaluation_panel,
    reset_evaluation_panel,
    ConsensusVerifier,
    VerificationOutcome,
    VerificationResult as ConsensusVerificationResult,
    QualityGate,
    get_consensus_verifier,
    reset_consensus_verifier,
    MetaPolicyMemory,
    PolicyRule,
    RuleCategory,
    AdmissibilityResult,
    get_meta_policy_memory,
    reset_meta_policy_memory,
    MetacognitiveMonitor,
    AnomalyScore,
    get_metacognitive_monitor,
    reset_metacognitive_monitor,
    InspectorGuard,
    InspectionResult,
    RiskLevel,
    IssuePattern,
    GuardStats,
    get_inspector_guard,
    reset_inspector_guard,
    ConfidenceCalibrator,
    CalibratedConfidence,
    ConfidenceBias,
    AgentCalibrationProfile,
    CalibratorStats,
    get_confidence_calibrator,
    reset_confidence_calibrator,
    TrajectoryScorer,
    TrajectoryResult,
    AgentTrajectory,
    ConformityAnalysis,
    get_trajectory_scorer,
    reset_trajectory_scorer,
    UncertaintyPropagator,
    PropagationSignal,
    UncertaintyLevel,
    ChainSummary,
    PropagatorStats,
    get_uncertainty_propagator,
    reset_uncertainty_propagator,
    FailureClassifier,
    FailureCategory,
    Classification,
    ClassifierStats,
    get_failure_classifier,
    reset_failure_classifier,
    FaultDetector,
    FaultStatus,
    AgentStatus,
    get_fault_detector,
    reset_fault_detector,
    TaskComplexity as ReasoningTaskComplexity,
    estimate_complexity,
    should_monitor_metacognition,
)

# Hive Mind exports (48 items)
from core.intelligence.hive_mind import (
    HiveMindState,
    UserBreakpoint,
    RetentionDecision,
    IndependentAnalysis,
    AnalysisComparison,
    Disagreement,
    DebateArgument,
    DebateResult,
    AgentSpec,
    AgentArchitecture,
    ExecutionIssue,
    MonitoredStepResult,
    FailureDiagnosis,
    RetryDecision,
    KnowledgeConsolidation,
    AgentRetention,
    BreakpointOption,
    BreakpointRequest,
    BreakpointResponse,
    AgentRegistry,
    CostEstimator,
    HiveMindContextManager,
    StrategyBlacklist,
    UserInteractionHandler,
    AdaptiveDebateConfig,
    DebateParams,
    TaskComplexity as HiveTaskComplexity,
    TrueHiveMind,
    HiveMindResult,
    SwarmBridge,
    SwarmDelegationResult,
    HivePhase,
    suggest_mode_for_subtask,
    create_bridge_for_phase,
    SagaManager,
    PhaseCheckpoint,
    SagaContext,
    PHASE_ORDER,
    PHASE_GUARDS,
    PhaseCoordinator,
    PhaseState,
    PhaseTransition,
    TransitionResult,
    get_phase_coordinator,
    reset_phase_coordinator,
    ConsensusTracker,
    TopicConsensus,
    ConsensusReport,
    get_consensus_tracker,
    reset_consensus_tracker,
    PhaseAuditLogger,
    DecisionAudit,
    PhaseAuditReport,
    AuditPattern,
    AuditStats,
    get_phase_audit_logger,
    reset_phase_audit_logger,
    MultiAgentReflexion,
    AgentReflection,
    ReflexionSynthesis,
    ReflexionMode,
    ReflexionStats,
    get_multi_agent_reflexion,
    reset_multi_agent_reflexion,
)

__all__ = [
    # Swarm (96 items)
    "AgentInvocationResult",
    "AgentProfile",
    "AgentPool",
    "create_default_pool",
    "CollaborationMode",
    "ModeCharacteristics",
    "MODE_CHARACTERISTICS",
    "get_mode_characteristics",
    "get_all_modes",
    "get_adversarial_modes",
    "get_parallel_modes",
    "suggest_mode_for_complexity",
    "TaskComplexity",
    "TaskDomain",
    "TaskAnalysis",
    "TaskAnalyzer",
    "AgentAssignment",
    "ModeProposal",
    "ModeSelector",
    "NegotiationStatus",
    "NegotiationProposal",
    "HybridNegotiationMessage",
    "NegotiationResult",
    "NegotiationProtocol",
    "extract_negotiate_json",
    "ExecutionStatus",
    "AgentResponse",
    "ExecutionContext",
    "ExecutionResult",
    "ModeExecutor",
    "ParallelExecutor",
    "SequentialExecutor",
    "LeadSupportExecutor",
    "PingPongExecutor",
    "SpecialistExecutor",
    "RedBlueExecutor",
    "EXECUTOR_REGISTRY",
    "get_executor",
    "SwarmPhase",
    "SwarmResult",
    "HybridSwarmEngine",
    "SessionStatus",
    "SessionMode",
    "AgentSession",
    "TaskSession",
    "SwarmSessionManager",
    "generate_task_id",
    "TaskCompletionValidator",
    "CompletionCriteria",
    "ValidationResult",
    "get_adaptive_max_rounds",
    "SwarmService",
    "SwarmServiceResult",
    "SwarmStatus",
    "SwarmTaskQueue",
    "SwarmTask",
    "SwarmTaskStatus",
    "QueueStats",
    "get_task_queue",
    "reset_task_queue",
    "ResultAggregator",
    "MergeStrategy",
    "MergeResult",
    "AggregatorStats",
    "get_aggregator",
    "reset_aggregator",
    "StrategyMemory",
    "StrategyRecord",
    "ModeEffectiveness",
    "ModeSuggestion",
    "StrategyStats",
    "get_strategy_memory",
    "reset_strategy_memory",
    "NegotiationTracker",
    "NegotiationTurn",
    "NegotiationRecord",
    "NegotiationStats",
    "get_negotiation_tracker",
    "reset_negotiation_tracker",
    "ModeEffectivenessEvaluator",
    "ModeEvaluation",
    "ModeEffectivenessSummary",
    "EvaluatorStats",
    "get_mode_evaluator",
    "reset_mode_evaluator",
    "AgentRoleTracker",
    "RoleAssignment",
    "AgentRoleProfile",
    "RoleTrackerStats",
    "get_role_tracker",
    "reset_role_tracker",
    "DynamicRoleAssigner",
    "CapabilityProposal",
    "RoleScore",
    "RoleAssignmentResult",
    "RoleType",
    "AssignerStats",
    "get_dynamic_role_assigner",
    "reset_dynamic_role_assigner",
    "ScalingHeuristicEvaluator",
    "ScalingRecommendation",
    "CoordinationType",
    "TaskCharacteristic",
    "ScalingStats",
    "get_scaling_heuristics",
    "reset_scaling_heuristics",
    # Evolution (30 items)
    "EvolutionManager",
    "EvolutionService",
    "EvolutionServiceResult",
    "_get_evolution_service",
    "MutationProposal",
    "BrainstormResult",
    "ChildCreationResult",
    "EvaluationResult",
    "PromotionResult",
    "ArchiveResult",
    "EvolutionResult",
    "SpecializationResult",
    "EvolutionStatus",
    "EvolutionContext",
    "EvolutionPhaseStatus",
    "load_lineage",
    "add_child",
    "get_ancestry",
    "sign_birth_certificate",
    "run_benchmarks",
    "compare_to_parent",
    "select_winner",
    "ChildValidator",
    "EvolutionValidationResult",
    "FullValidationResult",
    "SafetyGate",
    "AutoPromotionDecision",
    "TieredValidator",
    "ValidationTier",
    "TieredValidationResult",
    "TierResult",
    "AgentReaper",
    "ReaperConfig",
    "ReaperReport",
    "ArchivalCandidate",
    "AutoSpecializer",
    "SpecializationConfig",
    "SpecializationProposal",
    "DomainProfile",
    "MutationTracker",
    "MutationRecord",
    "AgentPerformance",
    "LineageNode",
    "get_mutation_tracker",
    "reset_mutation_tracker",
    "StrategyPerformanceTracker",
    "StrategyApplication",
    "StrategyMetrics",
    "StrategyRecommendation",
    "TrackerStats",
    "get_strategy_tracker",
    "reset_strategy_tracker",
    # Reasoning (60+ items)
    "GOT_AVAILABLE",
    "GraphOfThought",
    "ThoughtNode",
    "ThoughtGraph",
    "ThoughtStatus",
    "ThoughtType",
    "ThoughtEvaluator",
    "ThoughtScore",
    "ThoughtEvaluationResult",
    "ThoughtEvaluatorStats",
    "get_thought_evaluator",
    "reset_thought_evaluator",
    "ReasoningQualityScorer",
    "ReasoningEvaluation",
    "AgentReasoningProfile",
    "ScorerStats",
    "get_quality_scorer",
    "reset_quality_scorer",
    "CognitiveDegradationDetector",
    "DegradationSignal",
    "DegradationReason",
    "Mitigation",
    "DetectorStats",
    "get_degradation_detector",
    "reset_degradation_detector",
    "EvaluationPanel",
    "EvalDimension",
    "DimensionScore",
    "PanelResult",
    "get_evaluation_panel",
    "reset_evaluation_panel",
    "ConsensusVerifier",
    "VerificationOutcome",
    "ConsensusVerificationResult",
    "QualityGate",
    "get_consensus_verifier",
    "reset_consensus_verifier",
    "MetaPolicyMemory",
    "PolicyRule",
    "RuleCategory",
    "AdmissibilityResult",
    "get_meta_policy_memory",
    "reset_meta_policy_memory",
    "MetacognitiveMonitor",
    "AnomalyScore",
    "get_metacognitive_monitor",
    "reset_metacognitive_monitor",
    "InspectorGuard",
    "InspectionResult",
    "RiskLevel",
    "IssuePattern",
    "GuardStats",
    "get_inspector_guard",
    "reset_inspector_guard",
    "ConfidenceCalibrator",
    "CalibratedConfidence",
    "ConfidenceBias",
    "AgentCalibrationProfile",
    "CalibratorStats",
    "get_confidence_calibrator",
    "reset_confidence_calibrator",
    "TrajectoryScorer",
    "TrajectoryResult",
    "AgentTrajectory",
    "ConformityAnalysis",
    "get_trajectory_scorer",
    "reset_trajectory_scorer",
    "UncertaintyPropagator",
    "PropagationSignal",
    "UncertaintyLevel",
    "ChainSummary",
    "PropagatorStats",
    "get_uncertainty_propagator",
    "reset_uncertainty_propagator",
    "FailureClassifier",
    "FailureCategory",
    "Classification",
    "ClassifierStats",
    "get_failure_classifier",
    "reset_failure_classifier",
    "FaultDetector",
    "FaultStatus",
    "AgentStatus",
    "get_fault_detector",
    "reset_fault_detector",
    "ReasoningTaskComplexity",
    "estimate_complexity",
    "should_monitor_metacognition",
    # Hive Mind (48 items)
    "HiveMindState",
    "UserBreakpoint",
    "RetentionDecision",
    "IndependentAnalysis",
    "AnalysisComparison",
    "Disagreement",
    "DebateArgument",
    "DebateResult",
    "AgentSpec",
    "AgentArchitecture",
    "ExecutionIssue",
    "MonitoredStepResult",
    "FailureDiagnosis",
    "RetryDecision",
    "KnowledgeConsolidation",
    "AgentRetention",
    "BreakpointOption",
    "BreakpointRequest",
    "BreakpointResponse",
    "AgentRegistry",
    "CostEstimator",
    "HiveMindContextManager",
    "StrategyBlacklist",
    "UserInteractionHandler",
    "AdaptiveDebateConfig",
    "DebateParams",
    "HiveTaskComplexity",
    "TrueHiveMind",
    "HiveMindResult",
    "SwarmBridge",
    "SwarmDelegationResult",
    "HivePhase",
    "suggest_mode_for_subtask",
    "create_bridge_for_phase",
    "SagaManager",
    "PhaseCheckpoint",
    "SagaContext",
    "PHASE_ORDER",
    "PHASE_GUARDS",
    "PhaseCoordinator",
    "PhaseState",
    "PhaseTransition",
    "TransitionResult",
    "get_phase_coordinator",
    "reset_phase_coordinator",
    "ConsensusTracker",
    "TopicConsensus",
    "ConsensusReport",
    "get_consensus_tracker",
    "reset_consensus_tracker",
    "PhaseAuditLogger",
    "DecisionAudit",
    "PhaseAuditReport",
    "AuditPattern",
    "AuditStats",
    "get_phase_audit_logger",
    "reset_phase_audit_logger",
    "MultiAgentReflexion",
    "AgentReflection",
    "ReflexionSynthesis",
    "ReflexionMode",
    "ReflexionStats",
    "get_multi_agent_reflexion",
    "reset_multi_agent_reflexion",
]

__version__ = "12.4.0"
