"""
Mode Selector - Sprint 9 Hybrid Swarm Engine

Selects the optimal collaboration mode using:
1. TaskAnalysis (complexity, domains)
2. DyLAN importance scores (AgentPool)
3. Mode characteristics matching
4. Historical performance

Works with AgentPool to provide data-driven mode selection.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from datetime import datetime

from .collaboration_modes import (
    CollaborationMode,
    ModeCharacteristics,
    MODE_CHARACTERISTICS,
    get_mode_characteristics
)
from .task_analyzer import TaskAnalysis, TaskComplexity, TaskDomain
from .agent_metrics import AgentPool, AgentProfile

# V7.6 Phase 10b: Memory-Augmented Mode Selection (lazy import)
_SUCCESS_MEMORY_AVAILABLE = False
try:
    from ..memory.success_memory import SuccessMemory
    _SUCCESS_MEMORY_AVAILABLE = True
except ImportError:
    SuccessMemory = None


@dataclass
class AgentAssignment:
    """Assignment of an agent to a role in a collaboration mode"""
    agent_id: str
    role: str  # "lead", "support", "red", "blue", "equal", "specialist"
    subtask: Optional[str] = None
    confidence: float = 0.5


@dataclass
class ModeProposal:
    """
    Proposal for a collaboration mode.

    Generated by ModeSelector, may be modified by negotiation.
    """
    mode: CollaborationMode
    confidence: float  # 0.0-1.0
    agent_assignments: List[AgentAssignment]
    reasoning: str
    alternatives: List[Tuple[CollaborationMode, float]] = field(
        default_factory=list
    )
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict:
        return {
            "mode": self.mode.value,
            "confidence": round(self.confidence, 3),
            "agent_assignments": [
                {
                    "agent_id": a.agent_id,
                    "role": a.role,
                    "subtask": a.subtask,
                    "confidence": round(a.confidence, 3)
                }
                for a in self.agent_assignments
            ],
            "reasoning": self.reasoning,
            "alternatives": [
                {"mode": m.value, "score": round(s, 3)}
                for m, s in self.alternatives[:3]
            ],
            "timestamp": self.timestamp.isoformat()
        }


class ModeSelector:
    """
    Selects optimal collaboration mode using DyLAN scoring.

    Combines task analysis with agent performance history
    to recommend the best collaboration mode.

    V7.6 Phase 10b: Supports memory-augmented selection using
    SuccessMemory to boost modes that worked for similar tasks.
    """

    # V7.6 Phase 10b: Memory boost constants
    MEMORY_BOOST_HIGH = 0.25    # High similarity (>0.5)
    MEMORY_BOOST_MEDIUM = 0.15  # Medium similarity (>0.3)
    MEMORY_BOOST_LOW = 0.08     # Low similarity (>0.2)
    MEMORY_MIN_SIMILARITY = 0.2  # Minimum similarity to apply boost

    # V7.6 Phase 10d: Session-aware scoring weights
    DYLAN_WEIGHT = 0.7          # DyLAN importance weight (70%)
    SESSION_WEIGHT = 0.3        # Session success rate weight (30%)

    def __init__(
        self,
        agent_pool: Optional[AgentPool] = None,
        history_weight: float = 0.3,
        success_memory: Optional["SuccessMemory"] = None
    ):
        """
        Initialize ModeSelector.

        Args:
            agent_pool: AgentPool with performance history
            history_weight: Weight given to historical performance (0-1)
            success_memory: V7.6 Phase 10b - SuccessMemory for memory-augmented selection
        """
        self.agent_pool = agent_pool
        self.history_weight = history_weight
        self.success_memory = success_memory
        self.selection_history: List[Dict] = []

        # V7.6 Phase 10b: Track memory-influenced selections
        self._last_memory_match: Optional[Dict] = None

    def select_mode(
        self,
        task_analysis: TaskAnalysis,
        available_agents: Optional[List[AgentProfile]] = None
    ) -> ModeProposal:
        """
        Select optimal collaboration mode for a task.

        V7.6 Phase 10b: Consults SuccessMemory to boost modes that
        worked for similar tasks.

        Args:
            task_analysis: Analysis of the task
            available_agents: Override agents (uses pool if None)

        Returns:
            ModeProposal with recommended mode and assignments
        """
        # Reset memory match tracker
        self._last_memory_match = None

        # Get agents
        if available_agents is None and self.agent_pool:
            available_agents = self.agent_pool.get_active_agents()

        if not available_agents:
            # Fallback: create default profiles
            available_agents = self._create_default_agents()

        # Score all modes
        mode_scores: Dict[CollaborationMode, float] = {}
        for mode in CollaborationMode:
            score = self._score_mode(mode, task_analysis, available_agents)
            mode_scores[mode] = score

        # V7.6 Phase 10b: Memory-Augmented Selection
        memory_boost_mode = None
        memory_boost_info = None
        if self.success_memory:
            memory_boost_mode, memory_boost_info = self._apply_memory_boost(
                task_analysis, mode_scores
            )

        # Select best mode
        best_mode = max(mode_scores, key=mode_scores.get)
        best_score = mode_scores[best_mode]

        # Generate alternatives (sorted by score)
        sorted_modes = sorted(
            mode_scores.items(),
            key=lambda x: x[1],
            reverse=True
        )
        alternatives = [(m, s) for m, s in sorted_modes if m != best_mode]

        # Assign agents
        assignments = self._assign_agents(
            best_mode, task_analysis, available_agents
        )

        # Generate reasoning (V7.6: include memory influence)
        reasoning = self._generate_reasoning(
            best_mode, task_analysis, mode_scores, memory_boost_info
        )

        proposal = ModeProposal(
            mode=best_mode,
            confidence=best_score,
            agent_assignments=assignments,
            reasoning=reasoning,
            alternatives=alternatives
        )

        # Record selection
        self._record_selection(task_analysis, proposal)

        return proposal

    def _score_mode(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """
        Score a mode for the given task and agents.

        Combines:
        - Complexity fit
        - Domain fit
        - Agent importance scores (DyLAN)
        - Historical performance
        """
        char = get_mode_characteristics(mode)
        score = 0.0

        # 1. Complexity fit (30%)
        complexity_fit = self._score_complexity_fit(char, analysis)
        score += complexity_fit * 0.30

        # 2. Domain fit (25%)
        domain_fit = self._score_domain_fit(char, analysis, agents)
        score += domain_fit * 0.25

        # 3. Agent importance scores - DyLAN (25%)
        dylan_fit = self._score_dylan_fit(mode, analysis, agents)
        score += dylan_fit * 0.25

        # 4. Requirements fit (20%)
        requirements_fit = self._score_requirements_fit(char, analysis)
        score += requirements_fit * 0.20

        return score

    def _score_complexity_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis
    ) -> float:
        """Score how well mode complexity matches task"""
        task_complexity_normalized = analysis.complexity.value / 5.0
        diff = abs(char.complexity_affinity - task_complexity_normalized)
        return 1.0 - diff

    def _score_domain_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """
        Score how well agent strengths match task domains.

        V7.5 Phase 5b: Agent-agnostic scoring based on capabilities
        and DyLAN scores, not hardcoded agent names.
        """
        if not agents:
            return 0.5  # Neutral if no agents

        primary_domain = analysis.primary_domain.value.lower()
        score = 0.0

        # Score based on how well available agents match the domain
        for agent in agents:
            capabilities_lower = [c.lower() for c in agent.capabilities]

            # Direct capability match
            if primary_domain in capabilities_lower:
                score += 0.4
            # Substring match (e.g., "coding" in "python_coding")
            elif any(primary_domain in cap for cap in capabilities_lower):
                score += 0.25

            # DyLAN importance for this domain
            dylan_score = agent.get_task_importance(primary_domain)
            score += dylan_score * 0.2

        # Normalize by agent count (max ~0.6 per agent contribution)
        score = score / max(len(agents), 1)

        # Legacy compatibility: check mode strength fits (still useful for mode characteristics)
        if hasattr(char, 'gemini_strength_fit') and primary_domain in char.gemini_strength_fit:
            score += 0.1
        if hasattr(char, 'claude_strength_fit') and primary_domain in char.claude_strength_fit:
            score += 0.1

        return min(1.0, score)

    def _score_dylan_fit(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> float:
        """
        Score using DyLAN importance scores from agent history.

        V7.6 Phase 10d: Now uses session-aware scoring when SuccessMemory
        is available, combining DyLAN scores with session success rates.
        """
        if not agents:
            return 0.5

        primary_domain = analysis.primary_domain.value
        scores = []

        for agent in agents:
            # V7.6 Phase 10d: Use session-aware score if pool supports it
            if self.agent_pool and self.success_memory:
                score = self.agent_pool.get_session_aware_score(
                    agent_id=agent.agent_id,
                    task_type=primary_domain,
                    success_memory=self.success_memory,
                    dylan_weight=self.DYLAN_WEIGHT
                )
            else:
                # Fallback to pure DyLAN
                score = agent.get_task_importance(primary_domain)

            scores.append(score)

        if not scores:
            return 0.5

        # For modes that benefit from specialist, reward high variance
        # For modes that need collaboration, reward balanced scores
        avg_score = sum(scores) / len(scores)

        if mode == CollaborationMode.SPECIALIST:
            # Reward when one agent clearly better
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return min(1.0, 0.5 + variance)
        else:
            # Reward balanced scores for collaborative modes
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return max(0.0, 1.0 - variance)

    def _score_requirements_fit(
        self,
        char: ModeCharacteristics,
        analysis: TaskAnalysis
    ) -> float:
        """Score based on task requirements"""
        score = 0.5  # Base score

        # Web requirement → prefer parallel (can search while coding)
        if analysis.requires_web and char.parallelism_benefit > 0.5:
            score += 0.2

        # Deep reasoning → prefer ping-pong or lead-support
        if analysis.requires_deep_reasoning:
            if char.mode in [CollaborationMode.PING_PONG, CollaborationMode.LEAD_SUPPORT]:
                score += 0.2

        # Iteration → prefer ping-pong
        if analysis.requires_iteration:
            if char.mode == CollaborationMode.PING_PONG:
                score += 0.3

        # Security → require RED_BLUE
        if analysis.needs_adversarial_mode:
            if char.adversarial:
                score += 0.5
            else:
                score -= 0.3

        return max(0.0, min(1.0, score))

    def _assign_agents(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: List[AgentProfile]
    ) -> List[AgentAssignment]:
        """
        Assign agents to roles based on mode and task.

        V7.5 Phase 5b: Agent-agnostic assignment using capability-based
        selection. Agents are ranked by DyLAN scores and capabilities,
        not by hardcoded names (Gemini/Claude).
        """
        if not agents:
            return []

        primary_domain = analysis.primary_domain.value

        # V7.5 Phase 5b: Get ranked agents by capability for this domain
        # V7.6 Phase 10d: Now uses session-aware scoring when available
        if self.agent_pool:
            # Use session-aware ranking if success_memory available
            if self.success_memory:
                # Rank by hybrid score (DyLAN + session success)
                ranked_agents = sorted(
                    agents,
                    key=lambda a: self.agent_pool.get_session_aware_score(
                        agent_id=a.agent_id,
                        task_type=primary_domain,
                        success_memory=self.success_memory,
                        dylan_weight=self.DYLAN_WEIGHT
                    ),
                    reverse=True
                )
            else:
                # Fallback to capability-based selection
                ranked_agents = self.agent_pool.select_agents_by_capability(
                    domain=primary_domain,
                    count=len(agents)
                )
        else:
            # Fallback: rank by DyLAN importance for the domain
            ranked_agents = sorted(
                agents,
                key=lambda a: a.get_task_importance(primary_domain),
                reverse=True
            )

        # Need at least 2 agents for most modes
        if len(ranked_agents) < 2 and mode not in [CollaborationMode.SPECIALIST]:
            # Try to use what we have
            if ranked_agents:
                return [AgentAssignment(
                    agent_id=ranked_agents[0].agent_id,
                    role="specialist",
                    confidence=0.6
                )]
            return []

        assignments = []
        assigned_ids = set()

        def get_next_best(exclude: set) -> Optional[AgentProfile]:
            """Get next best agent not already assigned."""
            for agent in ranked_agents:
                if agent.agent_id not in exclude:
                    return agent
            return None

        if mode == CollaborationMode.PARALLEL:
            # Top 2 agents work in parallel
            for idx in range(min(2, len(ranked_agents))):
                agent = ranked_agents[idx]
                subtask = "research_and_web" if idx == 0 and analysis.requires_web else f"subtask_{idx+1}"
                assignments.append(AgentAssignment(
                    agent_id=agent.agent_id,
                    role="equal",
                    subtask=subtask,
                    confidence=0.8 - (idx * 0.1)  # Slightly lower for second agent
                ))
                assigned_ids.add(agent.agent_id)

        elif mode == CollaborationMode.SEQUENTIAL:
            # Best agent first, second-best agent second
            first = ranked_agents[0] if ranked_agents else None
            second = get_next_best({first.agent_id} if first else set())

            if first:
                assignments.append(AgentAssignment(
                    agent_id=first.agent_id,
                    role="first",
                    confidence=0.8
                ))
            if second:
                assignments.append(AgentAssignment(
                    agent_id=second.agent_id,
                    role="second",
                    confidence=0.7
                ))

        elif mode == CollaborationMode.LEAD_SUPPORT:
            # Best agent is lead, second-best is support
            lead = ranked_agents[0] if ranked_agents else None
            support = get_next_best({lead.agent_id} if lead else set())

            if lead:
                # Calculate confidence based on agent's domain fit
                lead_importance = lead.get_task_importance(primary_domain)
                assignments.append(AgentAssignment(
                    agent_id=lead.agent_id,
                    role="lead",
                    confidence=min(0.95, 0.6 + lead_importance * 0.35)
                ))
            if support:
                assignments.append(AgentAssignment(
                    agent_id=support.agent_id,
                    role="support",
                    confidence=0.6
                ))

        elif mode == CollaborationMode.PING_PONG:
            # Top 2 agents alternate
            for idx in range(min(2, len(ranked_agents))):
                agent = ranked_agents[idx]
                assignments.append(AgentAssignment(
                    agent_id=agent.agent_id,
                    role="equal",
                    confidence=0.7
                ))

        elif mode == CollaborationMode.SPECIALIST:
            # Single best agent for the domain
            specialist = ranked_agents[0] if ranked_agents else None
            if specialist:
                importance = specialist.get_task_importance(primary_domain)
                # Higher confidence if agent has explicit capability match
                capabilities_lower = [c.lower() for c in specialist.capabilities]
                has_capability = primary_domain.lower() in capabilities_lower
                confidence = 0.9 if has_capability else min(0.85, 0.5 + importance * 0.35)

                assignments.append(AgentAssignment(
                    agent_id=specialist.agent_id,
                    role="specialist",
                    confidence=confidence
                ))

        elif mode == CollaborationMode.RED_BLUE:
            # Best agent is blue (proposer), second is red (attacker)
            # In adversarial mode, the top agent proposes, second attacks
            blue = ranked_agents[0] if ranked_agents else None
            red = get_next_best({blue.agent_id} if blue else set())

            if blue:
                assignments.append(AgentAssignment(
                    agent_id=blue.agent_id,
                    role="blue",
                    subtask="propose_and_defend",
                    confidence=0.8
                ))
            if red:
                assignments.append(AgentAssignment(
                    agent_id=red.agent_id,
                    role="red",
                    subtask="attack_and_verify",
                    confidence=0.8
                ))

        return assignments

    # =========================================================================
    # V7.6 Phase 10b: Memory-Augmented Selection
    # =========================================================================

    def _apply_memory_boost(
        self,
        analysis: TaskAnalysis,
        mode_scores: Dict[CollaborationMode, float]
    ) -> Tuple[Optional[CollaborationMode], Optional[Dict]]:
        """
        Apply memory boost to mode scores based on similar tasks.

        V7.6 Phase 10b: Consults SuccessMemory to find similar tasks
        and boosts the mode that worked for them.

        Args:
            analysis: TaskAnalysis with raw_input description.
            mode_scores: Dictionary of mode scores (modified in-place).

        Returns:
            Tuple of (boosted_mode, boost_info) or (None, None).
        """
        if not self.success_memory:
            return None, None

        # Get task description
        description = getattr(analysis, "raw_input", "")
        if not description:
            return None, None

        # Find similar tasks
        result = self.success_memory.get_best_mode_for_similar(
            query=description,
            min_similarity=self.MEMORY_MIN_SIMILARITY
        )

        if not result:
            return None, None

        recommended_mode, similar_task_id, similarity = result

        # Map mode string to enum
        boosted_mode = None
        for mode in CollaborationMode:
            if mode.value.lower() == recommended_mode.lower():
                boosted_mode = mode
                break

        if not boosted_mode or boosted_mode not in mode_scores:
            return None, None

        # Calculate boost based on similarity level
        if similarity > 0.5:
            boost = self.MEMORY_BOOST_HIGH
        elif similarity > 0.3:
            boost = self.MEMORY_BOOST_MEDIUM
        else:
            boost = self.MEMORY_BOOST_LOW

        # Apply boost
        original_score = mode_scores[boosted_mode]
        mode_scores[boosted_mode] = min(1.0, original_score + boost)

        # Store match info
        boost_info = {
            "mode": boosted_mode.value,
            "similar_task_id": similar_task_id,
            "similarity": round(similarity, 3),
            "boost_applied": boost,
            "original_score": round(original_score, 3),
            "new_score": round(mode_scores[boosted_mode], 3)
        }

        self._last_memory_match = boost_info

        return boosted_mode, boost_info

    def _generate_reasoning(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        scores: Dict[CollaborationMode, float],
        memory_boost_info: Optional[Dict] = None
    ) -> str:
        """
        Generate human-readable reasoning for mode selection.

        V7.5 Phase 5b: Agent-agnostic reasoning.
        V7.6 Phase 10b: Includes memory influence if applicable.
        """
        char = get_mode_characteristics(mode)

        reasons = []

        # V7.6 Phase 10b: Memory-augmented selection
        if memory_boost_info and memory_boost_info.get("mode") == mode.value:
            task_id = memory_boost_info.get("similar_task_id", "unknown")[:12]
            similarity = memory_boost_info.get("similarity", 0)
            reasons.append(f"Boosted by memory (similar to {task_id}, {similarity:.0%})")

        # Complexity reason
        complexity_name = analysis.complexity.name.lower()
        reasons.append(f"Task complexity: {complexity_name}")

        # Domain reason
        domain_str = ", ".join(d.value for d in analysis.domains[:2])
        reasons.append(f"Domains: {domain_str}")

        # Agent fit reason - V7.5 Phase 5b: Use generic message
        if analysis.recommended_lead:
            reasons.append(f"Recommended lead: {analysis.recommended_lead}")
        else:
            reasons.append("Agent selection based on capability scores")

        # Mode-specific reason
        reasons.append(char.when_to_use)

        # Score
        reasons.append(f"Selection confidence: {scores[mode]:.0%}")

        return " | ".join(reasons)

    def _find_best_spawned_specialist(
        self,
        spawned_agents: List[AgentProfile],
        analysis: TaskAnalysis
    ) -> Optional[AgentProfile]:
        """
        Find the best spawned agent for a specialist role.

        V7.5 HIVE MIND: Matches spawned agent capabilities against task domains.

        Args:
            spawned_agents: List of spawned agents
            analysis: Task analysis with domain info

        Returns:
            Best matching AgentProfile or None
        """
        if not spawned_agents:
            return None

        primary_domain = analysis.primary_domain.value.lower()
        best_agent = None
        best_score = 0.0

        for agent in spawned_agents:
            # Check if agent's capabilities match task domain
            capabilities_lower = [c.lower() for c in agent.capabilities]

            # Direct domain match
            if primary_domain in capabilities_lower:
                score = 1.0
            # Partial match (domain word in capability)
            elif any(primary_domain in cap for cap in capabilities_lower):
                score = 0.8
            # Check DyLAN importance for this domain
            else:
                score = agent.get_task_importance(primary_domain)

            if score > best_score:
                best_score = score
                best_agent = agent

        # Only return if score is above threshold
        if best_score >= 0.5:
            return best_agent
        return None

    def _assign_spawned_specialist(
        self,
        spawned_agents: List[AgentProfile],
        analysis: TaskAnalysis
    ) -> List[AgentAssignment]:
        """
        Assign a spawned agent as specialist (fallback when no internal agents).

        V7.5 HIVE MIND: Used when gemini/claude are unavailable.
        """
        best = self._find_best_spawned_specialist(spawned_agents, analysis)
        if best:
            return [AgentAssignment(
                agent_id=best.agent_id,
                role="specialist",
                confidence=0.7
            )]

        # Last resort: use first available spawned agent
        if spawned_agents:
            return [AgentAssignment(
                agent_id=spawned_agents[0].agent_id,
                role="specialist",
                confidence=0.5
            )]

        return []

    def _create_default_agents(self) -> List[AgentProfile]:
        """Create default agent profiles when pool unavailable"""
        return [
            AgentProfile(
                agent_id="gemini_primary",
                provider="gemini",
                model="gemini-3-pro-preview"
            ),
            AgentProfile(
                agent_id="claude_opus",
                provider="claude",
                model="claude-opus-4-5-20251101"
            )
        ]

    def _record_selection(
        self,
        analysis: TaskAnalysis,
        proposal: ModeProposal
    ):
        """Record selection for future analysis"""
        record = {
            "timestamp": datetime.now().isoformat(),
            "task_complexity": analysis.complexity.name,
            "primary_domain": analysis.primary_domain.value,
            "selected_mode": proposal.mode.value,
            "confidence": proposal.confidence
        }
        self.selection_history.append(record)

        # Keep only last 100 selections
        if len(self.selection_history) > 100:
            self.selection_history = self.selection_history[-100:]

    def get_selection_stats(self) -> Dict:
        """Get statistics about mode selections"""
        if not self.selection_history:
            return {"total_selections": 0}

        mode_counts: Dict[str, int] = {}
        for record in self.selection_history:
            mode = record["selected_mode"]
            mode_counts[mode] = mode_counts.get(mode, 0) + 1

        avg_confidence = sum(
            r["confidence"] for r in self.selection_history
        ) / len(self.selection_history)

        return {
            "total_selections": len(self.selection_history),
            "mode_distribution": mode_counts,
            "average_confidence": round(avg_confidence, 3)
        }
