# NEXUS V6.0 - Installation Script
# Creates global PowerShell command: nexus6

param(
    [string]$InstallPath,
    [switch]$SkipDependencies
)

Clear-Host
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  NEXUS V6.0 - THE OMNISCIENT REPL" -ForegroundColor Cyan
Write-Host "  Installation Script" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Determine install path
if (-not $InstallPath) {
    $InstallPath = Join-Path $env:LOCALAPPDATA "NEXUS_V6"
}

Write-Host "Installation Settings:" -ForegroundColor Yellow
Write-Host "  Target Directory: $InstallPath"
Write-Host "  Global Command:   nexus6"
Write-Host ""

# Check if already installed
if (Test-Path $InstallPath) {
    Write-Host "NEXUS V6 is already installed at: $InstallPath" -ForegroundColor Yellow
    $response = Read-Host "Overwrite existing installation? (y/N)"

    if ($response -ne 'y' -and $response -ne 'Y') {
        Write-Host "Installation cancelled." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To install anyway, run:" -ForegroundColor Cyan
        Write-Host "  Remove-Item -Recurse -Force '$InstallPath'" -ForegroundColor Cyan
        Write-Host "  .\install_v6.ps1" -ForegroundColor Cyan
        exit 0
    }

    Write-Host "Removing old installation..." -ForegroundColor Cyan
    Remove-Item -Recurse -Force $InstallPath -ErrorAction SilentlyContinue
}

# Create installation directory
Write-Host "Creating installation directory..." -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $InstallPath | Out-Null

# Get source directory
$SourceDir = $PSScriptRoot

Write-Host "Copying NEXUS V6 files..." -ForegroundColor Cyan

# Core files
Copy-Item "$SourceDir\nexus6.py" $InstallPath -Force
Copy-Item "$SourceDir\requirements_v6.txt" $InstallPath -Force

# Copy core modules
Copy-Item "$SourceDir\core" $InstallPath -Recurse -Force -Exclude "__pycache__","*.pyc"

# Copy prompts
Copy-Item "$SourceDir\prompts" $InstallPath -Recurse -Force

# Copy documentation
Copy-Item "$SourceDir\README.md" $InstallPath -Force
Copy-Item "$SourceDir\NEXUS.md" $InstallPath -Force
Copy-Item "$SourceDir\docs" $InstallPath -Recurse -Force -ErrorAction SilentlyContinue

# Copy/create configuration
if (Test-Path "$SourceDir\.env") {
    Copy-Item "$SourceDir\.env" $InstallPath -Force
    Write-Host "  [OK] .env file copied" -ForegroundColor Green
} else {
    Write-Host "  [!] No .env file found - you'll need to create one" -ForegroundColor Yellow
}

# Create batch launcher
Write-Host "Creating nexus6.bat launcher..." -ForegroundColor Cyan

$BatchContent = @"
@echo off
REM NEXUS V6.0 - Global Launcher
REM This file is automatically generated by install_v6.ps1

cd /d "$InstallPath"
python nexus6.py %*
"@

$BatchPath = Join-Path $InstallPath "nexus6.bat"
Set-Content -Path $BatchPath -Value $BatchContent -Encoding ASCII

Write-Host "  [OK] Created: $BatchPath" -ForegroundColor Green

# Update User PATH
Write-Host "Updating system PATH..." -ForegroundColor Cyan

$UserPath = [Environment]::GetEnvironmentVariable("Path", "User")

if ($UserPath -like "*$InstallPath*") {
    Write-Host "  [OK] Already in PATH" -ForegroundColor Green
} else {
    # Add to PATH
    $NewPath = "$UserPath;$InstallPath"
    [Environment]::SetEnvironmentVariable("Path", $NewPath, "User")
    Write-Host "  [OK] Added to User PATH" -ForegroundColor Green
}

# Refresh current session PATH
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

# Install Python dependencies
if (-not $SkipDependencies) {
    Write-Host ""
    Write-Host "Installing Python dependencies..." -ForegroundColor Cyan

    $PipResult = & python -m pip install -r "$InstallPath\requirements_v6.txt" 2>&1

    if ($LASTEXITCODE -eq 0) {
        Write-Host "  [OK] Dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "  [!] Dependency installation failed" -ForegroundColor Yellow
        Write-Host "      Run manually: pip install -r requirements_v6.txt" -ForegroundColor Yellow
    }
} else {
    Write-Host ""
    Write-Host "[!] Skipped dependency installation (-SkipDependencies)" -ForegroundColor Yellow
}

# Bootstrap verification
Write-Host ""
Write-Host "Running bootstrap verification..." -ForegroundColor Cyan

$BootstrapResult = & python "$InstallPath\nexus6.py" --verify 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "  [OK] Bootstrap verification passed" -ForegroundColor Green
} else {
    Write-Host "  [!] Bootstrap verification failed" -ForegroundColor Yellow
    Write-Host "      You may need to configure CLIs or dependencies" -ForegroundColor Yellow
}

# Success message
Write-Host ""
Write-Host "================================================" -ForegroundColor Green
Write-Host "  NEXUS V6.0 Installation Complete!" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Green
Write-Host ""

Write-Host "Installation Summary:" -ForegroundColor Cyan
Write-Host "  Location:        $InstallPath"
Write-Host "  Launcher:        nexus6.bat"
Write-Host "  Global Command:  nexus6"
Write-Host ""

Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  1. RESTART your PowerShell terminal" -ForegroundColor White
Write-Host "     (Required for PATH changes to take effect)" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  2. Test installation:" -ForegroundColor White
Write-Host "     PS> nexus6" -ForegroundColor Cyan
Write-Host ""
Write-Host "  3. Create workspace:" -ForegroundColor White
Write-Host "     PS> mkdir my-project" -ForegroundColor Cyan
Write-Host "     PS> cd my-project" -ForegroundColor Cyan
Write-Host "     PS> nexus6" -ForegroundColor Cyan
Write-Host ""

Write-Host "Documentation:" -ForegroundColor Yellow
Write-Host "  Quick Start: $InstallPath\docs\QUICKSTART.md"
Write-Host "  NEXUS.md:    $InstallPath\NEXUS.md"
Write-Host "  README:      $InstallPath\README.md"
Write-Host ""

Write-Host "Troubleshooting:" -ForegroundColor Yellow
Write-Host "  If 'nexus6' not found after restart:"
Write-Host "    - Verify PATH: [Environment]::GetEnvironmentVariable('Path', 'User')"
Write-Host "    - Run manually: python '$InstallPath\nexus6.py'"
Write-Host ""

Write-Host "Happy coding with NEXUS V6! 🚀" -ForegroundColor Cyan
Write-Host ""
